### ISSUE TITLE
使用你的例子里面没有cron.WithSecond()方法

### ISSUE THREAD

**Issue by phpnewnew** [lizongying/cron#1]
begin := time.Now()
	logger := cron.NewLoggerStdout()
	c := cron.New(cron.WithSecond(), cron.WithStdout())
	id := c.MustAddJob("every 3 seconds", func() {
		logger.Info(time.Now().Sub(begin))
	})

**Comment by lizongying** [comment]
只有main分支支持`cron.WithSecond()`。
<img width="680" alt="image" src="https://github.com/lizongying/cron/assets/16871545/3a570e90-f996-4fec-820d-e22074b1fec5">
simple分支不再使用，因为默认支持，就去掉了这个选项。建议使用这个分支。[simple-v2](https://github.com/lizongying/cron/tree/simple-v2)
![image](https://github.com/lizongying/cron/assets/16871545/687ae939-11af-4746-9f83-bc60dc68963b)

**Comment by phpnewnew** [comment]
ok谢谢 可以在使用说明没标注一下。
